# Generated by Django 3.1 on 2020-08-24 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='group',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='artists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='auth.group'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.scene'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='stuffs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='auth.group'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='auth.group'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='scene',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
