# Generated by Django 3.1 on 2020-08-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0002_auto_20200824_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='teachers',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='auth.group'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.CharField(default='model', max_length=20),
        ),
    ]
