# Generated by Django 3.1 on 2020-08-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0004_signuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='auth.group'),
        ),
    ]
