# Generated by Django 3.1 on 2020-08-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200830_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'permissions': (('item_exhibition', 'Can change item in exhibition'), ('tool_exhibition', 'Can change tool in exhibition'), ('scene_exhibition', 'Can change scene in exhibition'), ('admin_exhibition', 'Can change scene in exhibition'))},
        ),
    ]
