# Generated by Django 3.1 on 2020-09-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200830_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='angle',
            field=models.FloatField(default=0.0),
        ),
    ]
